/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jclouds.glacier.predicates.validators;

import org.testng.annotations.Test;

@Test(groups = "unit", testName = "DescriptionValidatorTest")
public class DescriptionValidatorTest {

   private static final DescriptionValidator VALIDATOR = new DescriptionValidator();

   public void testValidate() {
      VALIDATOR.validate("This is a valid description");
      VALIDATOR.validate("This_is*A#valid@Description");
      VALIDATOR.validate("This~Is~A~Valid~Description");
      VALIDATOR.validate("&Valid$Description");
      VALIDATOR.validate("");
   }

   @Test(expectedExceptions = IllegalArgumentException.class)
   public void testIllegalCharacters() {
      VALIDATOR.validate(Character.toString((char) 31));
      VALIDATOR.validate(Character.toString((char) 127));
   }

   @Test(expectedExceptions = IllegalArgumentException.class)
   public void testDescriptionTooLong() {
      VALIDATOR.validate("INVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTION" +
      		"INVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRI" +
      		"PTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDD" +
      		"ESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINV" +
      		"ALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDNAMEINVAL" +
      		"IDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTION" +
      		"INVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRI" +
      		"PTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDD" +
      		"ESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINV" +
      		"INVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRI" +
            "PTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDD" +
            "ESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINV" +
            "INVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRI" +
            "PTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDD" +
            "ESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINVALIDDESCRIPTIONINV" +
      		"ALIDDESCRIPTION");
   }
}
